/*
 * Copyright (c) 2012, Nguyen Quoc Dinh
 * All rights reserved.
 */


/**
 * \file
 *         Collect network tree from leave to gateway generated by routing algo (i.e ROLL for current Contiki NWK layer)
 * \author
 *         Nguyen Quoc Dinh <nqdinh@hui.edu.vn>
 */
#ifndef __NETWORKTREE_H__
#define __NETWORKTREE_H__

#include "contiki-net.h"
#include "net/uip-ds6.h"
/** \brief NetworkTree process */
PROCESS_NAME(networktreed_process);

#define LISTEN_PORT	1200

#define VERSION_01	1

#define REQUEST		0
#define FORCEREQUEST		1
#define RESPONSE	2

#define MAX_BUF_SIZE	484		//TODO: verify this number

#define FAILURE			-1
#define ERR_NO_ERROR	0
#define ERR_MEMORY_ALLOCATION	1

//struct of address displace each hop a packet traveled through

typedef union varbind_t {
	uip_ipaddr_t parentaddr;
	u16_t gwrport;				//gateway remote port
} varbind_t;

struct networktree_object_t {
	u8_t version;
	u8_t type;
	u8_t id;
	struct varbind_t varbind_object;
} networktree_object_t;

#endif
