/*
 * Copyright (c) 2012, Nguyen Quoc Dinh
 * All rights reserved.
 */


/**
 * \file
 *         Collect network tree from leave to gateway generated by routing algo (i.e ROLL for current Contiki NWK layer)
 * \author
 *         Nguyen Quoc Dinh <nqdinh@hui.edu.vn>
 */
#ifndef __NETWORKTREE_H__
#define __NETWORKTREE_H__

#include "contiki-net.h"
#include "net/uip-ds6.h"
/** \brief NetworkTree process */
PROCESS_NAME(networktreed_process);

#define LISTEN_PORT	1200

#define VERSION_01	1

#define REQUEST		0
#define RESPONSE	1

//struct of address displace each hop a packet traveled through
struct address_t{
	u8_t hopcount;
	//address
	struct address_t *next_ptr;
};

struct hops_chain_t{
	u8_t hopnumber;
	struct address_t *address_object;
};

struct networktree_object_t {
	u8_t version;
	u8_t type;
	u8_t id;
	struct hops_chain_t	*hops_chain_object;
};

#endif
