/*
 * Copyright (c) 2012, Nguyen Quoc Dinh
 * All rights reserved.
 */


/**
 * \file
 *         Collect network tree from leave to gateway generated by routing algo (i.e ROLL for current Contiki NWK layer)
 * \author
 *         Nguyen Quoc Dinh <nqdinh@hui.edu.vn>
 */
#include <stdio.h>
#include <string.h>
#include <stdlib.h>

#include "contiki.h"

#include "networktreed.h"
#include "nwktr-dispatcher.h"

#define DEBUG DEBUG_PRINT
#include "net/uip-debug.h"
//debug
#include "net/rpl/rpl.h"

/* UDP connection */
static struct uip_udp_conn *udpconn;

PROCESS(networktreed_process, "NetworkTree daemon process");

/*
void
collect_common_net_print(void)
{
  rpl_dag_t *dag;
  uip_ds6_route_t *r;

   //Let's suppose we have only one instance
  dag = rpl_get_any_dag();
  if(dag->preferred_parent != NULL) {
    PRINTF("Preferred parent: ");
    PRINT6ADDR(&dag->preferred_parent->addr);
    PRINTF("\n");
  }
  for(r = uip_ds6_route_list_head();
      r != NULL;
      r = list_item_next(r)) {
    PRINT6ADDR(&r->ipaddr);
  }
  PRINTF("---\n");
}
*/
static void udp_handler(process_event_t ev, process_data_t data){
	char rst;
	//collect_common_net_print();

	if (ev == tcpip_event && uip_newdata()){
		rst = nwkgraph_processing((uint8_t*)uip_appdata, uip_datalen(), udpconn);		//change this name

		PRINTF("exit with %d\n", rst);
	}
}

/*-----------------------------------------------------------------------------------*/
/*
 *  Entry point of the SNMP server.
 */
PROCESS_THREAD(networktreed_process, ev, data) {
	PROCESS_BEGIN();

	udpconn = udp_new(NULL, UIP_HTONS(0), NULL);
	udp_bind(udpconn, UIP_HTONS(LISTEN_PORT));

    /* init MIB */
	PRINTF("start the process\n");

	while(1) {
		PROCESS_YIELD();
		if(ev == tcpip_event) {
			udp_handler(ev, data);
		}
	}

	PROCESS_END();
}
