/**
 * \file
 *         Collect network tree from mote to gateway generated by routing algo
 *         (i.e ROLL for current Contiki NWK layer)
 * \author
 *         Jan 2013 Nguyen Quoc Dinh <nqdinh@hui.edu.vn>
 */

#include <stdio.h>
#include <string.h>
#include "man.h"
#include "man-dispatcher.h"

#define DEBUG DEBUG_PRINT
#include "net/uip-debug.h"

static struct uip_udp_conn *client_conn;
static man_conf_t man_conf;

/*---------------------------------------------------------------------------*/
PROCESS(man_process, "Management process");

/*---------------------------------------------------------------------------*/
static void man_udp_handler(void) {
	if(uip_newdata()) {
/*		((char *)uip_appdata)[uip_datalen()] = 0;
		printf("New uIP data: '%s'\n", uip_appdata);
		PRINT6ADDR(&man_conf->mnaddr);
		printf("port = %u\n", man_conf->mnrport);
*/
		char rst;
		rst = man_processing((uint8_t*)uip_appdata, uip_datalen(), &man_conf, client_conn);
		PRINTF("ManUDP handler return with %d\n", rst);
	}
}
/*---------------------------------------------------------------------------*/
static void man_conf_init(man_conf_t *conf){
	conf->send_active = SEND_ACTIVE_NO;
	conf->update_freq_in_sec = DEFAULT_UPDATE_PERIOD;	//this value may update via snmp
}
/*---------------------------------------------------------------------------*/
PROCESS_THREAD(man_process, ev, data)
{
	static struct etimer period_timer, wait_timer;
	PROCESS_BEGIN();

	man_conf_init(&man_conf);

	/* new connection with remote host */
	//tcp_listen(UIP_HTONS(COLLECTD_CLIENT_PORT));
	client_conn = udp_new(NULL, UIP_HTONS(0), NULL);
	udp_bind(client_conn, UIP_HTONS(COLLECTD_CLIENT_PORT));

	/* Send a packet every 60-62 seconds. */
	etimer_set(&period_timer, CLOCK_SECOND * DEFAULT_UPDATE_PERIOD);

	while(1) {
		PROCESS_WAIT_EVENT();
		//send update (collected data)
		if(ev == PROCESS_EVENT_TIMER) {
			if (data == &period_timer) {
				etimer_reset(&period_timer);		//TODO: reset the period from man_conf.update freq
				if (man_conf.send_active == SEND_ACTIVE_YES)
					etimer_set(&wait_timer, random_rand() % (CLOCK_SECOND * RANDWAIT));

			} else if(data == &wait_timer) {
				/* Time to send the data */
				PRINTF("Time to send the data\n");
				man_common_send(client_conn, &man_conf);
			}
		}
		//receive a request (here, expected a request to begin to send update)
		if(ev == tcpip_event) {
			man_udp_handler();
		}
	}

	PROCESS_END();
}
/*---------------------------------------------------------------------------*/
